---
title: Telling the Bees
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: debbie.maxwell@york.ac.uk
description: 'Telling the Bees was a digital making and design project that explored
  the stories and possible futures of honey bees and their role in our world.

'
baseurl: 
url: 
twitter_username: tellthebee
twitter_hashtag: tellingthebees
github_username: 
logo: logo.png
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
